#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {status,plan,getControl,getCapability,getContract,getProfile,getSections,evidenceContract,validate} from './runtime-api.js';import {install} from './installer.js';import {RUNTIME_ROOT} from './paths.js';import {RUNTIME_VERSION,EXPECTED_CORE_REVISION} from './config.js';
const args=process.argv.slice(2);const cmd=args.shift()||'help';const has=x=>args.includes(x);const value=(x,d=null)=>{const i=args.indexOf(x);return i>=0?args[i+1]:d};const out=x=>console.log(has('--json')?JSON.stringify(x,null,2):(typeof x==='string'?x:JSON.stringify(x,null,2)));
async function deps(){const names=['@modelcontextprotocol/server','@modelcontextprotocol/node','zod'];const r={};for(const n of names){try{await import(n);r[n]='installed'}catch{r[n]='missing'}}return r}
try{
 if(cmd==='help'){console.log(`BizIQ Runtime ${RUNTIME_VERSION}\n\nCommands:\n  status [--json]\n  plan <request> [--json] [--industry X] [--creation-type X] [--mode Production|Prototype|...] [--fidelity High-Fidelity|Exploratory|Low-Fidelity]\n  get control <BQ-ID|capability>\n  get contract <slug>\n  get profile <industry>\n  get section <path> [stable-id]\n  validate core\n  validate operation <file.json>\n  validate operations-regressions\n  validate interaction-manifest <interaction.json>\n  validate evidence <evidence.json> [--plan runtime-plan.json] [--interaction-manifest interaction.json]\n  verify\n  doctor\n  install <skill|claude|gemini|vscode|cursor|openai|all> [--project DIR] [--dry-run]\n  mcp --stdio | --http [--host HOST] [--port PORT]\n  ui [--host HOST] [--port PORT]\n  version`);}
 else if(cmd==='version')console.log(`BizIQ Runtime ${RUNTIME_VERSION} / Core ${EXPECTED_CORE_REVISION}`);
 else if(cmd==='status')out(status());
 else if(cmd==='plan'){const skip=new Set();for(const flag of ['--industry','--creation-type','--mode','--fidelity']){const i=args.indexOf(flag);if(i>=0){skip.add(i);skip.add(i+1)}}for(const flag of ['--json']){const i=args.indexOf(flag);if(i>=0)skip.add(i)}const request=args.filter((_,i)=>!skip.has(i)).join(' ').trim();if(!request)throw new Error('plan requires a request string');out(plan(request,{industry:value('--industry')||undefined,creationType:value('--creation-type')||undefined,deliveryMode:value('--mode')||undefined,visualFidelity:value('--fidelity')||undefined}));}
 else if(cmd==='get'){const kind=args.shift(),q=args.shift();if(!q)throw new Error('get requires a target');if(kind==='control')out(getControl(q));else if(kind==='capability')out(getCapability(q));else if(kind==='evidence-contract')out(evidenceContract());else if(kind==='contract')out(getContract(q));else if(kind==='profile')out(getProfile(q));else if(kind==='section')out(getSections([{path:q,id:args.shift()}]));else throw new Error('get kind must be control|capability|evidence-contract|contract|profile|section');}
 else if(cmd==='validate'){const target=args.shift()||'core';const file=args.shift();out(validate({target,file,plan:value('--plan')||undefined,interactionManifest:value('--interaction-manifest')||undefined}));}
 else if(cmd==='verify'){const s=status();const v=validate({target:'core'});const o=validate({target:'operations-regressions'});out({ok:s.coreIntegrity==='PASS'&&v.ok&&o.ok,status:s,coreValidation:v,operationsRegression:o});process.exitCode=(s.coreIntegrity==='PASS'&&v.ok&&o.ok)?0:1;}
 else if(cmd==='doctor'){const s=status();const d=await deps();const nodeMajor=Number(process.versions.node.split('.')[0]);const report={ok:s.coreIntegrity==='PASS'&&nodeMajor>=20,node:process.versions.node,nodeOk:nodeMajor>=20,core:s,dependencies:d,mcpReady:Object.values(d).every(x=>x==='installed'),notes:[]};if(!report.mcpReady)report.notes.push('Core CLI/router works without MCP packages; run npm install before starting MCP transports.');out(report);process.exitCode=report.ok?0:1;}
 else if(cmd==='install'){const target=args.shift();if(has('--global'))throw new Error('Runtime 1.0 intentionally does not mutate global/home configuration automatically. Use platform-native global installers with the supplied adapters.');out(install(target,{project:value('--project',process.cwd()),dryRun:has('--dry-run')}));}
 else if(cmd==='mcp'){const script=has('--http')?'mcp-http.js':'mcp-stdio.js';const pass=args.filter(a=>!['--stdio','--http'].includes(a));const r=spawnSync(process.execPath,[path.join(RUNTIME_ROOT,'src',script),...pass],{stdio:'inherit'});process.exitCode=r.status??1;}
 else if(cmd==='ui'){const r=spawnSync(process.execPath,[path.join(RUNTIME_ROOT,'src','ui-server.js'),...args],{stdio:'inherit'});process.exitCode=r.status??1;}
 else throw new Error(`Unknown command: ${cmd}`);
}catch(e){console.error(`BizIQ Runtime: ${e.message}`);process.exitCode=2}
