import fs from 'node:fs';
import * as z from 'zod/v4';
import { McpServer } from '@modelcontextprotocol/server';
import { status, plan, getSections, getControl, getCapability, getContract, getProfile, compiler, evidenceContract, validate, core } from './runtime-api.js';
import { UI_FILE } from './paths.js';
import { RUNTIME_VERSION, EXPECTED_CORE_REVISION } from './config.js';

const UI_URI='ui://biziq/status';
const textResult=(x)=>({content:[{type:'text',text:typeof x==='string'?x:JSON.stringify(x,null,2)}],structuredContent:typeof x==='object'?x:{text:x}});
const safe=(fn)=>async(args)=>{try{return textResult(await fn(args||{}))}catch(e){return {isError:true,content:[{type:'text',text:`BizIQ Runtime error: ${e.message}`}]}}};
export function createBizIQServer(){
 const s=new McpServer({name:'biziq-runtime',title:'BizIQ Runtime',version:RUNTIME_VERSION,description:`Portable routing, retrieval, compilation context, and validation for BizIQ Core ${EXPECTED_CORE_REVISION}.`});
 s.registerTool('biziq_initialize',{title:'Initialize BizIQ',description:'Verify the vendored BizIQ core and return runtime/control-plane status.',inputSchema:z.object({}) ,annotations:{readOnlyHint:true,idempotentHint:true}},safe(()=>status()));
 s.registerTool('biziq_plan',{title:'Build BizIQ Plan',description:'Classify a request and return semantic/context/artifact graphs, phase-scoped capabilities, contract chains, retrieval budget, unresolved facts, evidence plan, and QA path.',inputSchema:z.object({request:z.string().min(1),creationType:z.string().optional(),industry:z.string().optional(),deliveryMode:z.enum(['Production','Prototype','MVP','Mockup','Wireframe','Demo','Concept']).optional(),visualFidelity:z.enum(['High-Fidelity','Exploratory','Low-Fidelity','Not-Applicable']).optional(),substantial:z.boolean().optional(),riskHints:z.array(z.string()).optional(),subindustry:z.string().optional(),jurisdiction:z.string().optional(),exposures:z.record(z.string(),z.boolean()).optional()}),annotations:{readOnlyHint:true,idempotentHint:true},_meta:{ui:{resourceUri:UI_URI,visibility:['model','app']}}},safe(a=>plan(a.request,a)));
 s.registerTool('biziq_get_sections',{title:'Read Exact BizIQ Sections',description:'Retrieve exact BizIQ files or stable-ID sections. Prefer stable IDs and the smallest needed retrieval.',inputSchema:z.object({items:z.array(z.object({path:z.string(),id:z.string().optional()})).min(1).max(20)}),annotations:{readOnlyHint:true,idempotentHint:true}},safe(a=>({sections:getSections(a.items)})));
 s.registerTool('biziq_get_capability',{title:'Get BizIQ Capability Section',description:'Retrieve one exact stable-ID capability section instead of a whole module.',inputSchema:z.object({query:z.string().min(1)}),annotations:{readOnlyHint:true,idempotentHint:true}},safe(a=>({capability:getCapability(a.query)})));
 s.registerTool('biziq_get_control',{title:'Get BizIQ Control',description:'Resolve a stable BQ control ID or capability name to canonical registry rows and its exact control section.',inputSchema:z.object({query:z.string().min(1)}),annotations:{readOnlyHint:true,idempotentHint:true}},safe(a=>({matches:getControl(a.query)})));
 s.registerTool('biziq_get_artifact_contract',{title:'Get Artifact Contract',description:'Retrieve one canonical artifact contract by slug.',inputSchema:z.object({slug:z.enum(['brand-identity','cli-developer-tool','dashboard','document-report','ecommerce-marketplace','email-campaign','fixed-format-document','local-service-website','marketing-creative','marketing-website','native-mobile-app','operations-workflow','presentation-deck','regulated-public-interface','saas-web-app','spreadsheet-financial-model'])}),annotations:{readOnlyHint:true,idempotentHint:true}},safe(a=>getContract(a.slug)));
 s.registerTool('biziq_get_profile',{title:'Get BizIQ Profile',description:'Resolve a canonical industry profile row.',inputSchema:z.object({industry:z.string().min(1)}),annotations:{readOnlyHint:true,idempotentHint:true}},safe(a=>({profile:getProfile(a.industry)})));
 s.registerTool('biziq_compile_feature',{title:'Feature Compiler Context',description:'Return the canonical feature compiler instructions for the model to apply to the active feature.',inputSchema:z.object({}),annotations:{readOnlyHint:true,idempotentHint:true}},safe(()=>compiler('feature')));
 s.registerTool('biziq_compile_component',{title:'Component Compiler Context',description:'Return the canonical component compiler instructions for the model to apply to the active component.',inputSchema:z.object({}),annotations:{readOnlyHint:true,idempotentHint:true}},safe(()=>compiler('component')));
 s.registerTool('biziq_compile_operation',{title:'Operations Compiler Context',description:'Return the canonical Operations 2.0 compiler instructions for a material procedure/runbook.',inputSchema:z.object({}),annotations:{readOnlyHint:true,idempotentHint:true}},safe(()=>compiler('operation')));
 s.registerTool('biziq_get_evidence_contract',{title:'Get Executable Evidence Contract',description:'Return the canonical tool-neutral evidence adapter contract and schema location.',inputSchema:z.object({}),annotations:{readOnlyHint:true,idempotentHint:true}},safe(()=>evidenceContract()));
 s.registerTool('biziq_validate',{title:'Validate BizIQ Work',description:'Run deterministic BizIQ core, Operations 2.0 regression, operational-procedure, or executable-evidence validation.',inputSchema:z.object({target:z.enum(['core','operation','operations-regressions','evidence']).default('core'),file:z.string().optional(),plan:z.string().optional()}),annotations:{readOnlyHint:true,idempotentHint:true}},safe(a=>validate(a)));
 s.registerTool('biziq_status',{title:'BizIQ Status',description:`Return Runtime ${RUNTIME_VERSION} and Core ${EXPECTED_CORE_REVISION} integrity/status.`,inputSchema:z.object({}),annotations:{readOnlyHint:true,idempotentHint:true},_meta:{ui:{resourceUri:UI_URI,visibility:['model','app']}}},safe(()=>status()));

 s.registerResource('BizIQ README','biziq://readme',{title:'BizIQ Authoritative README',mimeType:'text/markdown'},async uri=>({contents:[{uri:uri.href,mimeType:'text/markdown',text:core.read('README.md')}]}));
 s.registerResource('BizIQ Control Index','biziq://control-index',{title:'BizIQ Control Index',mimeType:'text/markdown'},async uri=>({contents:[{uri:uri.href,mimeType:'text/markdown',text:core.read('CONTROL_INDEX.md')}]}));
 s.registerResource('BizIQ Control Manifest','biziq://control-manifest',{title:'BizIQ Control Manifest',mimeType:'text/markdown'},async uri=>({contents:[{uri:uri.href,mimeType:'text/markdown',text:core.read('CONTROL_MANIFEST.md')}]}));
 for(const slug of ['brand-identity','cli-developer-tool','dashboard','document-report','ecommerce-marketplace','email-campaign','fixed-format-document','local-service-website','marketing-creative','marketing-website','native-mobile-app','operations-workflow','presentation-deck','regulated-public-interface','saas-web-app','spreadsheet-financial-model']) s.registerResource(`Contract: ${slug}`,`biziq://contract/${slug}`,{title:`BizIQ ${slug} contract`,mimeType:'text/markdown'},async uri=>({contents:[{uri:uri.href,mimeType:'text/markdown',text:core.contract(slug)}]}));
 const uiMeta={ui:{csp:{connectDomains:[],resourceDomains:[],frameDomains:[],baseUriDomains:[]},prefersBorder:true}};
 s.registerResource('BizIQ Runtime UI',UI_URI,{title:'BizIQ Runtime Status & Plan',description:'Interactive BizIQ plan/status surface with no external network dependencies.',mimeType:'text/html;profile=mcp-app',_meta:uiMeta},async uri=>({contents:[{uri:uri.href,mimeType:'text/html;profile=mcp-app',text:fs.readFileSync(UI_FILE,'utf8'),_meta:uiMeta}]}));
 s.registerPrompt('biziq-production-plan',{title:'BizIQ Production Plan',description:'Create a production execution plan using BizIQ routing before implementation.',argsSchema:z.object({request:z.string().min(1)})},async({request})=>({messages:[{role:'user',content:{type:'text',text:`Use BizIQ Runtime to plan this request before implementation. Retrieve only the required BizIQ sections, preserve production intent and truth boundaries, then execute and validate. Request: ${request}`}}]}));
 return s;
}
