# SPDX-FileCopyrightText: 2026 AIFENCE contributors
# SPDX-License-Identifier: AGPL-3.0-only
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aifence.serviceAccountName" . }}
  labels:
    {{- include "aifence.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}

{{- if and .Values.worker.enabled .Values.worker.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aifence.workerServiceAccountName" . }}
  labels:
    {{- include "aifence.labels" . | nindent 4 }}
    app.kubernetes.io/component: dispatcher
  {{- with .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}

{{- if and .Values.lifecycleWorker.enabled .Values.lifecycleWorker.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aifence.lifecycleServiceAccountName" . }}
  labels:
    {{- include "aifence.labels" . | nindent 4 }}
    app.kubernetes.io/component: lifecycle
  {{- with .Values.lifecycleWorker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}

{{- if and .Values.anchorWorker.enabled .Values.anchorWorker.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aifence.anchorServiceAccountName" . }}
  labels:
    {{- include "aifence.labels" . | nindent 4 }}
    app.kubernetes.io/component: audit-anchor
  {{- with .Values.anchorWorker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
